WebApp/Models/EmployeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class EmployeViewModel
    {
        public int Id { get; set; }

        public string Nom { get; set; }

        public string Prenom { get; set; }

        public DateTime DateNaissance { get; set; }

        public int Anciennete { get; set; }

        public string Biographie { get; set; }

        public ICollection<PostulationViewModel> Postulations { get; set; }

        public ICollection<FormationViewModel> Formations { get; set; }

        public ICollection<ExperienceViewModel> Experiences { get; set; }


    }
}

WebApp/Models/ExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }

        public int EmployeId { get; set; }

        public EmployeViewModel Employe { get; set; }

        public string Intitule { get; set; }

        public DateTime Date { get; set; }
    }
}

WebApp/Models/FormationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class FormationViewModel
    {
        public int Id { get; set; }

        public int EmployeId { get; set; }

        public EmployeViewModel Employe { get; set; }

        public string Intitule { get; set; }

        public DateTime DateFormation { get; set; }
    }
}

WebApp/Models/OffreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class OffreViewModel
    {
        public int Id { get; set; }

        public string Intitule { get; set; }

        public DateTime DateParution { get; set; }

        public string Description { get; set; }

        public float Salaire { get; set; }

        public string Responsable { get; set; }

        public int StatutId { get; set; }

        public StatutViewModel Statut { get; set; }

        public ICollection<PostulationViewModel> Postulations { get; set; }
    }
}

WebApp/Models/PostulationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class PostulationViewModel
    {
        public int Id { get; set; }
        public int EmployeId { get; set; }

        public EmployeViewModel Employe { get; set; }

        public DateTime DatePostulation { get; set; }

        public string Statut { get; set; }

        public int OffreId { get; set; }

        public OffreViewModel Offre { get; set; }
    }
}

WebApp/Models/StatutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class StatutViewModel
    {
        public int Id { get; set; }

        public string Libelle { get; set; }

        public ICollection<OffreViewModel> Offres { get; set; }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApp/Controllers/OffreController.cs
using Bll;
using Serveur.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class OffreController : Controller
    {
        public ActionResult Index(String searchString )
        {
            List<Offre> offres = Manager.Instance.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                offres = Manager.Instance.getOffresByTitle(searchString);
            }
            List<OffreViewModel> offresViewModels = new List<OffreViewModel>();

            foreach(Offre offre in offres)
            {
                offresViewModels.Add(new OffreViewModel
                { 
                    Id = offre.Id,
                    Intitule = offre.Intitule,
                    DateParution = offre.DateParution,
                    Description = offre.Description,
                    Salaire = offre.Salaire,
                    Responsable = offre.Responsable,
                });
            }
            return View(offresViewModels);
        }

        public ActionResult Detail(int id)
        {
            Offre offre = Manager.Instance.GetById(id);
            OffreViewModel offreViewModel = new OffreViewModel
            {
                Id = offre.Id,
                Intitule = offre.Intitule,
                DateParution = offre.DateParution,
                Description = offre.Description,
                Salaire = offre.Salaire,
                Responsable = offre.Responsable
            };

            return View(offreViewModel);
        }
    }
}

WebApp/Controllers/PostulationController.cs
using Bll;
using Serveur.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class PostulationController : Controller
    {
        // GET: Postulation
        public ActionResult Index()
        {
            List<Postulation> postulations = Manager.Instance.GetPostulationsByUser();
            List<PostulationViewModel> postulationsView = new List<PostulationViewModel>();
            Employe employe = Manager.Instance.GetEmploye();
            foreach(Postulation postulation in postulations)
            {
                PostulationViewModel viewModel = new PostulationViewModel();
                viewModel.Id = postulation.Id;
                viewModel.OffreId = postulation.OffreId;
                viewModel.DatePostulation = postulation.DatePostulation;
                viewModel.EmployeId = postulation.EmployeId;
                viewModel.Employe = new EmployeViewModel();
                viewModel.Employe.Id = employe.Id;
                viewModel.Employe.Nom = employe.Nom;
                viewModel.Employe.Prenom = employe.Prenom;
                viewModel.Employe.DateNaissance = employe.DateNaissance;
                viewModel.Employe.Anciennete = employe.Anciennete;
                viewModel.Employe.Biographie = employe.Biographie;
                
                postulationsView.Add(viewModel);
            }
            return View(postulationsView);
        }

        public ActionResult AddPostulation(int offreId)
        {
            Manager.Instance.AddPostulation(offreId);
            return View();
        }
    }
}

WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApp/Views/Offre/Detail.cshtml
@model WebApp.Models.OffreViewModel

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>OffreViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Intitule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Intitule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateParution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateParution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Responsable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Responsable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatutId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatutId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApp/Views/Offre/Index.cshtml
@model List<WebApp.Models.OffreViewModel>


@{
    ViewBag.Title = "Offre";
}

<h2>Offre</h2>
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<ul>
    @foreach (var item in Model)
    {
    <li>
        <div>@item.Intitule</div>
        <button><a href="@Url.Action("Detail", "Offre", new { id = item.Id })">Détails</a></button>
        <button><a href="@Url.Action("AddPostulation", "Postulation", new { offreId = item.Id })">Postuler</a></button>

    </li>
    }
</ul>

WebApp/Views/Postulation/AddPostulation.cshtml
@{
    ViewBag.Title = "PostulationValidate";
}

<h2>PostulationValidate</h2>
<h3>Félicitation vous avez postuler a une offre !</h3>

WebApp/Views/Postulation/Index.cshtml
@model IEnumerable<WebApp.Models.PostulationViewModel>

@{
    ViewBag.Title = "Liste des postulations";
}

<h2>Liste des postulations</h2>

<table class="table">
    <tr>
        <th>
           Employe name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatePostulation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OffreId)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employe.Prenom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatePostulation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Statut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OffreId)
        </td>
    </tr>
}

</table>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Offre", "Index", "Offre")</li>
                    <li>@Html.ActionLink("Postulation", "Index", "Postulation")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>